apiVersion: v1
kind: Service
metadata:
    name: "mdascluster-2b7f"
    labels:
        app: "mdascluster-2b7f"
spec:
    type: LoadBalancer
    ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
    selector:
        app: "mdascluster-2b7f"