name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-go@v3
   
    - name: Install Go linter
      run: wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.45.0
    
    - name: Run linter
      run: ./bin/golangci-lint run

    - name: Run tests
      run: go test ./src/tests/unit_test.go

    - name: Build project
      run: go build -o app .

    - name: Login to DockerHub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        

    - uses: azure/docker-login@v1
      with:
        login-server: gohello.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: build and push container image 
      run: |
          docker build . -t gohello.azurecr.io/gohello:alpine-latest
          docker push gohello.azurecr.io/gohello:alpine-latest
          
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mdascluster_kubeConfig }}
      id: login

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: gohello.azurecr.io
        container-registry-username: ${{ secrets.acr_gohello_username }}
        container-registry-password: ${{ secrets.acr_gohello_password }}
        secret-name: mdasclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          gohello.azurecr.io/mdascluster:${{ github.sha }}
        imagepullsecrets: |
          mdasclusterdockerauth