on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
    - name: install go linter
      run: wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.45.0
    - name: execute linter
      run: ./bin/golangci-lint run
    - name: Run tests
      run: go test ./src/tests/unit_test.go 