on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup docker image
      run: docker run -p 8090:8090  gohello.azurecr.io/mdascluster:alpine-latest