on: push

jobs:
  loginazure:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: gohello.azurecr.io
          username: ${{ secrets.acr_gohello_username }}
          password: ${{ secrets.acr_gohello_password }}
      - name: run docker image
        run: docker run -p 8090:8090 -d  gohello.azurecr.io/mdascluster:alpine-latest


